basePath: /
definitions:
  models.Message:
    properties:
      id:
        type: string
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Simple API for storing and retrieving messages.
  title: Message API
  version: "1.0"
paths:
  /messages:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Message'
            type: array
      summary: list messages
    post:
      consumes:
      - application/json
      parameters:
      - description: Message to create
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.Message'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Message'
      summary: create message
  /messages/{id}:
    get:
      parameters:
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
      summary: read message
swagger: "2.0"
