services:
  app:
    build: .
    image: message-api-goa
    platform: linux/amd64
    container_name: message-api-goa
    ports:
      - "8080:8080"

  proxy:
    image: nginx:alpine
    platform: linux/amd64
    container_name: message-api-proxy
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/templates/nginx-proxy.conf:ro
    ports:
      - "8081:8080"
    environment:
      NGINX_PORT: 8080
      PROXY_TARGET: http://app:8080
    command: /bin/sh -c "envsubst '$${NGINX_PORT} $${PROXY_TARGET}' < /etc/nginx/templates/nginx-proxy.conf > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - app

  docs:
    image: swaggerapi/swagger-ui
    platform: linux/amd64
    container_name: "message-api-docs"
    ports:
      - "8082:8080"
    environment:
       URL: http://localhost:8081/openapi.json
    depends_on:
      - proxy

# scratch for docs service before using proxy
# SWAGGER_JSON: /openapi.json
# volumes:
#  - ./gen/http/openapi.json:/openapi.json:ro
