openapi: 3.0.3
info:
    title: simple message service
    description: hello world http service for managing messages
    version: 0.0.1
servers:
    - url: http://localhost:8080/message
      description: hosts the message service
paths:
    /messages:
        get:
            tags:
                - message
            summary: list message
            operationId: message#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Message'
                                example:
                                    - id: Nostrum quia et placeat.
                                      text: Excepturi minima et reprehenderit aut dolor.
                                    - id: Nostrum quia et placeat.
                                      text: Excepturi minima et reprehenderit aut dolor.
                            example:
                                - id: Nostrum quia et placeat.
                                  text: Excepturi minima et reprehenderit aut dolor.
                                - id: Nostrum quia et placeat.
                                  text: Excepturi minima et reprehenderit aut dolor.
                                - id: Nostrum quia et placeat.
                                  text: Excepturi minima et reprehenderit aut dolor.
                                - id: Nostrum quia et placeat.
                                  text: Excepturi minima et reprehenderit aut dolor.
        post:
            tags:
                - message
            summary: create message
            operationId: message#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            text: g
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Message'
                            example:
                                id: Dolorum nulla eos et reiciendis.
                                text: Dolores officia veniam voluptatem consectetur sit.
    /messages/{id}:
        get:
            tags:
                - message
            summary: read message
            operationId: message#read
            parameters:
                - name: id
                  in: path
                  description: UUID of the message
                  required: true
                  schema:
                    type: string
                    description: UUID of the message
                    example: Vel sed alias perspiciatis.
                  example: Voluptatem nemo iusto debitis ut ipsam et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Message'
                            example:
                                id: Non sed dicta sapiente.
                                text: Voluptas eum earum.
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFoundError'
                            example:
                                message: Et nam dolor repellat unde nihil voluptas.
    /openapi.json:
        get:
            tags:
                - message
            summary: Download gen/http/openapi3.json
            operationId: message#/openapi.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                text:
                    type: string
                    description: Message text
                    example: 5p
                    minLength: 1
            example:
                text: z
            required:
                - text
        Message:
            type: object
            properties:
                id:
                    type: string
                    description: UUID of the message
                    example: Odio ratione consequatur omnis nisi nisi.
                text:
                    type: string
                    description: Message text
                    example: Eligendi aliquam.
            example:
                id: Nam aut adipisci ipsum.
                text: Facilis est officia numquam eveniet fugit asperiores.
            required:
                - id
                - text
        NotFoundError:
            type: object
            properties:
                message:
                    type: string
                    description: error message
                    example: Enim in earum reiciendis.
            example:
                message: Veritatis est autem explicabo.
            required:
                - message
tags:
    - name: message
      description: simple message service
